### PR TITLE
Delete an expense entry by index 

### LINKED ISSUE #7: Delete an expense entry
As an Accident-prone user, I can delete an expense entry so that I can remove incorrect entries.

### PR DESCRIPTION
**Pull request by Ariff1422**
Fixes #7                                                                                                                                                       
                  
Implements the `delete` command. Users can now remove an expense by its
1-based index (e.g. `delete 2`). Adds DeleteCommand, ExpenseList.deleteExpense(),
and Ui.showDeleteSuccess().

### CODE REVIEW

File: src/main/java/seedu/duke/Parser.java [hunk 1]
```diff
@@ -22,6 +23,8 @@ public static Command parse(String input) {
         switch (commandWord) {
         case "add":
             return parseAddCommand(parts.length > 1 ? parts[1] : "");
+        case "delete":
+            return new DeleteCommand(Integer.parseInt(parts[1].trim()));
```
Comment (AfshalG) [inline src/main/java/seedu/duke/Parser.java]: parts[1] will throw ArrayIndexOutOfBoundsException if the user types delete with no number. Should guard with if (parts.length < 2) and return an error command or throw a SpendTrackException.

File: src/test/java/seedu/duke/command/DeleteCommandTest.java [hunk 2]
```diff
@@ -0,0 +1,42 @@
...
+    private ExpenseList expenses;
+    private Ui ui;
+
+    @BeforeEach
+    void setUp() {
+        expenses = new ExpenseList();
+        ui = new Ui();
+        new AddCommand("Coffee", 4.50, "Food").execute(expenses, ui);
+        new AddCommand("MRT top-up", 10.00, "Transport").execute(expenses, ui);
+        new AddCommand("Textbook", 35.00, "Education").execute(expenses, ui);
```
Comment (AfshalG) [inline src/test/java/seedu/duke/command/DeleteCommandTest.java]: "Education" is not a valid category (valid ones: Food, Transport, Accommodation, Shopping, Entertainment, Others). Should use one of the valid categories to keep tests consistent with app behaviour. 

We can discuss later.

**Review by AfshalG — CHANGES_REQUESTED** [review]
Two bugs need fixing before merge: 
(1) Parser crashes on delete with no index, 
(2) DeleteCommand crashes on out-of-range index. Both should call ui.showError() instead of throwing uncaught exceptions. 
We can fix this now or after v1.0

Also one test uses an invalid category. 
This needs to be fixed.

Please fix and push - happy to re-review.

**Review by AfshalG — APPROVED** [review]
looks good. 

fix indentation in master branch
